README.md
actions/push
actions/start
actions/stop
config.yaml
layer.yaml
lib/charms/layer/docker_registry.py
reactive/docker_registry.py

Quite a few issues came up with the registry when it went into the real world.
- refactor auth (both token and htpasswd) to be consistent and more maintanable
- send required relation data for both proxy and registry clients
- better status messages to indicate when the registry is up/down/sideways
- readme updates to talk about the above
These have been pushed to --beta in `~containers/docker-registry-7`

charm updates

---

reactive/docker_registry.py

If the website relation is joined when there are no docker-registry
relations then the hook panics trying to update the clients. This change
checks the clients exist before attempting to update them.

Fix exception in website-relations-joined

---

README.md
config.yaml
lib/charms/layer/docker_registry.py

In order to solve https://launchpad.net/bugs/1808357 in our registry deployment, we need to be able to run a read-only instance of the registry. This branch adds a new storage-read-only config item which manipulates the "readonly" knob (https://docs.docker.com/registry/configuration/#readonly)

add storage-read-only config item, and honour it

---

.gitignore
config.yaml
layer.yaml
lib/charms/layer/docker_registry.py
reactive/docker_registry.py

https://bugs.launchpad.net/layer-docker-registry/+bug/1788891

Ability to add blobs for TLS

---

reactive/docker_registry.py

By default, haproxy will sit in front of docker-registry in active-passive mode, but we need to make sure the registry only answers to one master.. that is, make the docker-registry leader deal with communication with haproxy, and let followers be cool and report status as hot-standbys.

only inform proxies when we are a leader

---

lib/charms/layer/docker_registry.py

This allows your registry to work correctly if you're making the TLS
termination on a frontend. Not compatible with docker 1.7 and earlier.

set "relativeurls" to true in the registry config

---

README.md
layer.yaml
metadata.yaml
reactive/docker_registry.py

https://bugs.launchpad.net/layer-docker-registry/+bug/1815459
- send proxy data for all registry units (not just leader)
- ensure oldest peer is primary backend; others are backups
- fix issues in the proxy stanza
- s/all_services/services
- `all_services` should only be used when fronting haproxy itself by something like the apache2 rev proxy
- add health check params
Available in the beta channel at `cs:~containers/docker-registry-81`.

 update for multiple frontend proxies

---

reactive/docker_registry.py

Prior to revision 80(ish), this charm was setting the `all_services` key on the haproxy relation.  This should have been `services`.  Fix this for people that upgrade to post rev 80(ish) by explicitly nullifying this invalid key in the proxy handler.

clear invalid all_services key from proxy relation

---

README.md
actions.yaml
actions/images
actions/rmi

- Address https://bugs.launchpad.net/layer-docker-registry/+bug/1808200 with an action that lets operators remove registry images.  This is effectively a wrapper around `docker rmi`.
- Let the people list images while we're at it.  This is effectively `docker images`.
These actions have been released in charm rev 125, currently in the beta channel:
https://jujucharms.com/u/containers/docker-registry/125

New actions to list and remove images

---

README.md
config.yaml
lib/charms/layer/docker_registry.py

Couple storage-related updates:
- Expose "delete by digest" config capabilities.  This enables deletion of blobs and manifests via the rest api like:
```
curl -u "user:pass" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
-X DELETE https://<registryurl>:5000/v2/busybox/manifests/<sha256 hash>
```
- Persist local images. When using local storage, images live in the registry container's /var/lib/registry. Ensure this is a volume mount from the host so images persist across registry restarts.

config to delete by digest; host volume to persist local images

---

reactive/docker_registry.py

See https://bugs.launchpad.net/layer-docker-registry/+bug/1828532
Way back in the 60s (revision 60s, that is), we added some invalid config on the website relation for both leader and follower units.  In the 80s (rev 87, #26), we corrected this with valid config, and in the early 100s (rev 101, #28), we sanitized the website relation data. Unfortunately, as the above bug shows, this only cleaned up the invalid config on leader units.
This PR does a similar cleanup for non-leader units.

lp:1828532 scrub proxy relation data for all peers

---

exec.d/docker-compose/charm-pre-install

The pre-install script from [layer-docker](https://github.com/juju-solutions/layer-docker/blob/master/exec.d/docker-compose/charm-pre-install) installs things from pip, which doesn't work in offline environments. Since the registry doesn't need docker-compose, just stub it out so we can deploy this charm in offline environments.

stub out docker-compose charm-pre-install

---

reactive/docker_registry.py

The command is required to create /etc/docker/registry/htpasswd when
basic authentication is chosen.
[LP: #1829529](https://bugs.launchpad.net/layer-docker-registry/+bug/1829529)

Make sure htpasswd is available before configuring the registry

---

lib/charms/layer/docker_registry.py

Changed charm to write config.yml with 600 permissions.
Fixes: [#1832639](https://bugs.launchpad.net/layer-docker-registry/+bug/1832639)
LP:#1832639

Change permissions on config.yml

---

.gitignore
.travis.yml
layer.yaml
lib/charms/layer/docker_registry.py
reactive/docker_registry.py
templates/daemon.json
tests/conftest.py
tests/test_docker_registry.py
tox.ini

Refactor to update daemon.json through the docker layer api rather
than writing the file directly.
Depends on https://github.com/juju-solutions/layer-docker/pull/141
Testing steps followed:
```
juju deploy cs:~containers/docker-registry
juju config docker-registry \
auth-basic-user='admin' \
auth-basic-password='password'
```
Confirmed registry came up and I could login.
```
juju run --unit docker-registry/0 "docker login -u admin -p password 172.31.71.92:5000"
```
Upgraded to the new charm.
```
juju upgrade-charm docker-registry --switch /tmp/charm-builds/docker-registry
```
Confirmed I could still login, and `/etc/docker/daemon.json` contained the json from the `daemon-opts` charm config, with the `insecure-registries` key added in by the charm.
```
juju run -a docker-registry "cat …
```

Stop writing daemon.json directly

---

.github/workflows/tox.yaml
.travis.yml
reactive/docker_registry.py
tests/conftest.py
tests/test_docker_registry.py
tox.ini

Stop the registry and put the charm into a blocked status during the series upgrade.
Part of https://bugs.launchpad.net/layer-docker-registry/+bug/1869944

Add support for series upgrade

---

reactive/docker_registry.py

when the docker-registry relation is broken between docker-registry and containerd, this charm leaves `charm.docker-registry.client-configured` set.  When a new relation joins, this prevents the `configure_client` code from setting all the registry config again on the relation

clear client-configured flag when the docker-registry relation leaves

---

config.yaml
lib/charms/layer/docker_registry.py

This exposes docker registry "proxy" settings which configures it as a pull-through cache.
See https://docs.docker.com/registry/recipes/mirror/

Registry pull-through cache

---

tox.ini

pin python-libjuju as its breaking integration tests

pin python-libjuju to pre 3.0

---

lib/charms/layer/docker_registry.py

Part of the charm code was assuming that the registry would always
run on port 5000 within the docker container, however the registry
configuration file was being rendered with the registry-port
so the host to container port mapping was broken.
Just always listen on 5000 and use the port mapping to implement
the registry-port option.

Fix implementation of registry-port

---

.github/workflows/main.yaml
config.yaml
lib/charms/layer/docker_registry.py
reactive/docker_registry.py
tests/integration/test_docker_registry_integration.py
tests/unit/conftest.py
tests/unit/test_docker_registry.py
tox.ini

[LP:2049360](https://bugs.launchpad.net/layer-docker-registry/+bug/2049360)
This PR provides a new config option `storage-cache` that can be used to switch between 'redis' and 'inmemory' cache types:
https://distribution.github.io/distribution/about/configuration/#cache
More important for the linked bug, any other value will [disable the cache](https://github.com/distribution/distribution/blob/release/2.8/registry/handlers/app.go#L289-L292) altogether.
I've also added a unit test for this option, though this charm could use a lot more help in the coverage department :/

new storage cache config option

---

config.yaml
lib/charms/layer/docker_registry.py
tests/unit/test_docker_registry.py

All settings are described in the distribution specification: https://distribution.github.io/distribution/storage-drivers/s3/
Now registry users may choose one of 3 storages: filesystem, swift, s3. `filesystem` storage is the default option.
LP issue: https://bugs.launchpad.net/layer-docker-registry/+bug/2072783

Added s3 storage support

---

.github/workflows/main.yaml
config.yaml
lib/charms/layer/docker_registry.py
tests/unit/test_docker_registry.py

Added charm configuration option `storage-redirect-disable` which allows to configure distribution behavior for s3/swift object storages. We need to provide such an option because this charm could be deployed with private object storage(e.g. CEPH RADOS object storage) and in this case user can't download any artifacts from the registry.
In previous versions of charm storage redirect was disabled implicitly for swift storage only. Now behavior of charm should be more clear and understandable. The default behavior for swift wasn't changed.
\+ added unit tests and  fixed linter issues
LP bug: https://bugs.launchpad.net/layer-docker-registry/+bug/2080349

Added explicit configuration option `storage-redirect-disable` 
